name: runner-test

on:
  workflow_dispatch:
    inputs:
      PLATFORM:
        description: "Platform"
        required: false
        default: "self-hosted"
        type: choice
        options:
          - ubuntu-latest
          - self-hosted

jobs:
  test:
    runs-on: ${{ github.event.inputs.PLATFORM || 'self-hosted' }}
    steps:
      - name: Hello
        run: echo "runner test OK $(hostname)"
